### PR TITLE
Patches for german sapphire/ruby rev 1

### PR DESCRIPTION
**Pull request by EisPaprika**
Starters is tested and works fine. Spin crashes at the moment, working on that one. Fishing, bunny_hop not tested yet

### CODE REVIEW

**Comment by EisPaprika** [comment]
Fixed spin not working on german ruby rev 1 (caused a crash)

**Comment by 40Cakes** [comment]
Hey mate, thanks for these - hope you didn't spend too much time looking for them, looks like pret has added de ruby/sapphire 😭
I've added them to my PR #94, just need to get the bot to load them up if it detects a de ROM.

**Comment by EisPaprika** [comment]
ive got them all from pret, but multiple people suggested to still write a patch file with only used symbols instead of adding another 70k lines file

**Comment by 40Cakes** [comment]
Closed in favour of #147.

**Pull request closed without merging**
