### PR TITLE
Add support for MacOS

### PR DESCRIPTION
**Pull request by NopoTheGamer**
improves on #179

### CODE REVIEW

**Comment by 40Cakes** [comment]
> Is it _really_ necessary to have Homebrew installed in order to have libmgba installed? Should be possible without it, even though this might be the most convenient way.
> 
> Also, we're not checking dependencies for Windows or Linux either.

Agreed, and I don't think *automatically* installing a package with no y/n prompt is a good idea. 

Maybe we can just direct the users to https://mgba.io/downloads.html, download .dmg and install manually *or* suggest the user can install it easily with a command (if they have brew), then re-run the bot once done.

**Comment by NopoTheGamer** [comment]
> Agreed, and I don't think _automatically_ installing a package with no y/n prompt is a good idea.

It doesnt do that its just instructing users.

> Maybe we can just direct the users to [mgba.io/downloads.html](https://mgba.io/downloads.html), download .dmg

yeah thats probably a better idea

**Comment by 40Cakes** [comment]
> > Agreed, and I don't think _automatically_ installing a package with no y/n prompt is a good idea.
> 
> It doesnt do that its just instructing users.
> 
> > Maybe we can just direct the users to [mgba.io/downloads.html](https://mgba.io/downloads.html), download .dmg
> 
> yeah thats probably a better idea

Ah, brain fart. I read `subprocess.check_output(["brew",` and stopped there... My bad, I see you're just checking if it's installed.

**Comment by NopoTheGamer** [comment]
the dmg doesnt seem to install anything, so I dont think that works

**Comment by 40Cakes** [comment]
I have just updated the wiki page to include some info on Mac support & how to get started, this is all that is probably required, just use !rtfm on anyone asking for help on a Mac in Discord 😛 https://github.com/40Cakes/pokebot-gen3/wiki/%E2%9D%93-Getting-Started

--

# Supported Operating Systems
- Windows
- MacOS
- Linux, tested and confirmed working on the following distros:
  - Ubuntu 23.04, 23.10
  - Debian 12
  - Pop!_OS 22.04 LTS

# Requirements
Warning! If you are not running the bot in a Python [venv](https://docs.python.org/3/library/venv.html), a prompt will appear, asking to install required Python packages and download + extract [libmgba](https://github.com/hanzi/libmgba-py). If you're using Python for any other projects, it is **highly recommended** to use a venv to isolate these packages from your base environment.

## Windows
- [Python 3.12](https://www.python.org/downloads/windows/) **Windows installer 64-bit**

## MacOS
- [Python 3.12](https://www.python.org/downloads/macos/) **macOS 64-bit universal2 installer** or `brew install python@3.12`
- [mGBA 0.10.x](https://mgba.io/downloads.html) **macOS** or `brew install mgba`

Note: `brew` requires [Homebrew](https://brew.sh/) to be installed.

## Linux
- [Python 3.12](https://www.python.org/downloads/source/) or `sudo apt install python3.12`
- Install the following packages with `apt` or appropriate package manager: `sudo apt install python3-distutils python3-tk libmgba0.10 portaudio19-dev`
- If `libmgba0.10` is not available on your distro, you can manually install the mGBA 0.10.x .deb package which includes libmgba0.10 from [here](https://mgba.io/downloads.html)

**Comment by 40Cakes** [comment]
> the dmg doesnt seem to install anything, so I dont think that works

Well you probably already have it installed? If you remove it with brew does it do anything via the .dmg?

**Comment by NopoTheGamer** [comment]
> Well you probably already have it installed? If you remove it with brew does it do anything via the .dmg?

I did test after removing it from brew, it doesnt have an installer or anything it just gives you an .app that you run

**Comment by 40Cakes** [comment]
> > Well you probably already have it installed? If you remove it with brew does it do anything via the .dmg?
> 
> I did test after removing it from brew, it doesnt have an installer or anything it just gives you an .app that you run

Oh right so it's like a portable version, gotcha. I'm not too familiar with the Mac ecosystem...

**Pull request closed without merging**
