### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by U2EZNeko**
Combo box at bottom of "select profile" window.
Added various dark and black themes

### CODE REVIEW

**Comment by U2EZNeko** [comment]
Added like 20 more themes

**Comment by U2EZNeko** [comment]
More themes for WebUI

**Comment by 40Cakes** [comment]
There is just FAR too many themes for the bot IMHO, would prefer if it was just a simple light/dark theme.
I don't think we really need a theme selector either, would probably just be easier to use [Darkdetect](https://pypi.org/project/darkdetect/) and adjust accordingly to the user's OS preferences.

**Comment by 40Cakes** [comment]
- `_set_button_colour()` is not setting button colours at all with ttkthemes.
- Load save state window crashes in dark mode if there are too many save states, with the following error:
```
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Serial number of failed request:  297422
  Current serial number in output stream:  299385
```
image

image

**Pull request merged**
